#!/bin/sh -f

############################ BEGIN LICENSE BLOCK #############################
#                                                                            #
# Version: MPL 1.1/GPL 2.0/LGPL 2.1                                          #
#                                                                            #
# The contents of this file are subject to the Mozilla Public License        #
# Version 1.1 (the "License"); you may not use this file except in           #
# compliance with the License. You may obtain a copy of the License at       #
# http://www.mozilla.org/MPL/                                                #
#                                                                            #
# Software distributed under the License is distributed on an "AS IS" basis, #
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License   #
# for the specific language governing rights and limitations under the       #
# License.                                                                   #
#                                                                            #
# The Original Code is the PowerLoom KR&R System.                            ;
#                                                                            #
# The Initial Developer of the Original Code is                              #
# UNIVERSITY OF SOUTHERN CALIFORNIA, INFORMATION SCIENCES INSTITUTE          #
# 4676 Admiralty Way, Marina Del Rey, California 90292, U.S.A.               #
#                                                                            #
# Portions created by the Initial Developer are Copyright (C) 1996-2006      #
# the Initial Developer. All Rights Reserved.                                #
#                                                                            #
# Contributor(s):                                                            #
#                                                                            #
# Alternatively, the contents of this file may be used under the terms of    #
# either the GNU General Public License Version 2 or later (the "GPL"), or   #
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),   #
# in which case the provisions of the GPL or the LGPL are applicable instead #
# of those above. If you wish to allow use of your version of this file only #
# under the terms of either the GPL or the LGPL, and not to allow others to  #
# use your version of this file under the terms of the MPL, indicate your    #
# decision by deleting the provisions above and replace them with the notice #
# and other provisions required by the GPL or the LGPL. If you do not delete #
# the provisions above, a recipient may use your version of this file under  #
# the terms of any one of the MPL, the GPL or the LGPL.                      #
#                                                                            #
############################# END LICENSE BLOCK ##############################

# Version: powerloom,v 1.3 2006/05/16 06:33:31 hans Exp
#
# Run the C++ or Java version of the PowerLoom KR&R system under Unix
#
# Usage: powerloom [c++ | java] [{-e|--eval} STELLA-EXPRESSION [--batch]
#
# If the first argument is `c++' the C++ version of PowerLoom is run
# (if installed), if it is `java' the Java version is run (if
# installed); otherwise, if the C++ version is installed it will run
# that; if that is not installed, it will run the Java version.

# Example usage:
#
#    % powerloom --batch -e '(demo "equations" FALSE)'


POWERLOOM_ROOT=`dirname $0`

cd $POWERLOOM_ROOT

# C++ environment:
POWERLOOM_CPP=${POWERLOOM_ROOT}/native/cpp/powerloom/powerloom
LD_LIBRARY_PATH=:$POWERLOOM_ROOT/native/cpp/lib:/usr/local/lib
export LD_LIBRARY_PATH
# for Darwin systems:
DYLD_LIBRARY_PATH=:$POWERLOOM_ROOT/native/cpp/lib:/usr/local/lib
export DYLD_LIBRARY_PATH

# Java environment:
JAVA=java
JAVA_FLAGS=-Xmx256m
POWERLOOM_JAR=$POWERLOOM_ROOT/native/java/lib/powerloom.jar
STELLA_JAR=$POWERLOOM_ROOT/native/java/lib/stella.jar
SEP=`if uname | grep -iq "CYGWIN\|MINGW"; then echo ";"; else echo ":"; fi`
CLASSPATH=$POWERLOOM_JAR$SEP$STELLA_JAR

if [ ${1:-undefined} = "c++" ]; then
   shift 1
   echo Running C++ version of PowerLoom...
   exec $POWERLOOM_CPP "$@"
elif [ ${1:-undefined} = "java" ]; then
   shift 1
   echo Running Java version of PowerLoom...
   exec $JAVA $JAVA_FLAGS -classpath $CLASSPATH edu.isi.powerloom.PowerLoom "$@"
elif [ -f $POWERLOOM_CPP ]; then
   echo Running C++ version of PowerLoom...
   exec $POWERLOOM_CPP "$@"
else
   echo Running Java version of PowerLoom...
   exec $JAVA $JAVA_FLAGS -classpath $CLASSPATH edu.isi.powerloom.PowerLoom "$@"
fi
