#!/bin/bash -f

############################ BEGIN LICENSE BLOCK #############################
#                                                                            #
# Version: MPL 1.1/GPL 2.0/LGPL 2.1                                          #
#                                                                            #
# The contents of this file are subject to the Mozilla Public License        #
# Version 1.1 (the "License"); you may not use this file except in           #
# compliance with the License. You may obtain a copy of the License at       #
# http://www.mozilla.org/MPL/                                                #
#                                                                            #
# Software distributed under the License is distributed on an "AS IS" basis, #
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License   #
# for the specific language governing rights and limitations under the       #
# License.                                                                   #
#                                                                            #
# The Original Code is the PowerLoom KR&R System.                            ;
#                                                                            #
# The Initial Developer of the Original Code is                              #
# UNIVERSITY OF SOUTHERN CALIFORNIA, INFORMATION SCIENCES INSTITUTE          #
# 4676 Admiralty Way, Marina Del Rey, California 90292, U.S.A.               #
#                                                                            #
# Portions created by the Initial Developer are Copyright (C) 1996-2011      #
# the Initial Developer. All Rights Reserved.                                #
#                                                                            #
# Contributor(s):                                                            #
#                                                                            #
# Alternatively, the contents of this file may be used under the terms of    #
# either the GNU General Public License Version 2 or later (the "GPL"), or   #
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),   #
# in which case the provisions of the GPL or the LGPL are applicable instead #
# of those above. If you wish to allow use of your version of this file only #
# under the terms of either the GPL or the LGPL, and not to allow others to  #
# use your version of this file under the terms of the MPL, indicate your    #
# decision by deleting the provisions above and replace them with the notice #
# and other provisions required by the GPL or the LGPL. If you do not delete #
# the provisions above, a recipient may use your version of this file under  #
# the terms of any one of the MPL, the GPL or the LGPL.                      #
#                                                                            #
############################# END LICENSE BLOCK ##############################

# Version: powerloom,v 1.8 2011/04/16 00:39:44 hans Exp
#
# Run the C++ or Java version of the PowerLoom KR&R system under Unix
#
# Usage: powerloom [--c++|--java|--gui|--gui-only] [--help] [{-e|--eval} command] [--batch] ...
#
# If the first argument is `--c++' the C++ version of PowerLoom is run
# (if installed), if it is `--java' the plain Java version is run (if
# installed); if it is `--gui' the Java version is run and the PowerLoom
# GUI is started from it connecting to an embedded HTTP server; if it
# is `--gui-only', the GUI is run in standalone mode and can connect to
# any available PowerLoom server.  If nothing is specified, the Java
# version of PowerLoom is run.

# Example usage:
#
#    % powerloom --batch -e '(demo "equations" FALSE)'
#    % powerloom --gui
#    % powerloom --gui-only --host myhost --port 9999


POWERLOOM_ROOT=`dirname $0`

cd $POWERLOOM_ROOT

# C++ environment:
POWERLOOM_CPP=${POWERLOOM_ROOT}/native/cpp/powerloom/powerloom
LD_LIBRARY_PATH=:$POWERLOOM_ROOT/native/cpp/lib:/usr/local/lib
export LD_LIBRARY_PATH
# for Darwin systems:
DYLD_LIBRARY_PATH=:$POWERLOOM_ROOT/native/cpp/lib:/usr/local/lib
export DYLD_LIBRARY_PATH

# Java environment:
JAVA=java
JAVA_FLAGS=-Xmx256m
JAVA_LIBDIR=$POWERLOOM_ROOT/native/java/lib
STELLA_JAR=$JAVA_LIBDIR/stella.jar
POWERLOOM_JAR=$JAVA_LIBDIR/powerloom.jar
POWERLOOM_SERVER_JAR=$JAVA_LIBDIR/powerloom-server.jar
POWERLOOM_GUI_JAR=$JAVA_LIBDIR/powerloom-gui.jar
CASTOR_CORE_JAR=$JAVA_LIBDIR/castor-core.jar
CASTOR_JAR=$JAVA_LIBDIR/castor.jar
LOGGING_JAR=$JAVA_LIBDIR/commons-logging.jar

sep=`if uname | grep -iq "CYGWIN\|MINGW"; then echo ";"; else echo ":"; fi`
GUI_CLASSPATH=$POWERLOOM_GUI_JAR$sep$CASTOR_CORE_JAR$sep$CASTOR_JAR$sep$LOGGING_JAR
CLASSPATH=$GUI_CLASSPATH$sep$POWERLOOM_SERVER_JAR$sep$POWERLOOM_JAR$sep$STELLA_JAR


if [[ ${1:-undefined} = "--c++" || ${1:-undefined} = "c++" ]]; then
   shift 1
   echo Running C++ version of PowerLoom...
   exec $POWERLOOM_CPP "$@"
elif [[ ${1:-undefined} = "--java"  ||  ${1:-undefined} = "java" ]]; then
   shift 1
   echo Running Java version of PowerLoom...
   exec $JAVA $JAVA_FLAGS -classpath $CLASSPATH edu.isi.powerloom.PowerLoom "$@"
elif [[ ${1:-undefined} = "--gui" || ${1:-undefined} = "gui" ]]; then
   shift 1
   echo Running Java GUI version of PowerLoom...
   exec $JAVA $JAVA_FLAGS -classpath $CLASSPATH edu.isi.powerloom.PowerLoom --gui "$@"
elif [[ ${1:-undefined} = "--gui-only" || ${1:-undefined} = "gui-only" ]]; then
   shift 1
   echo Running standalone PowerLoom GUI...
   exec $JAVA $JAVA_FLAGS -classpath $GUI_CLASSPATH edu.isi.powerloom.gui.components.PowerloomApp "$@"
else
   echo Running Java version of PowerLoom...
   exec $JAVA $JAVA_FLAGS -classpath $CLASSPATH edu.isi.powerloom.PowerLoom "$@"
fi
